"""
Groupme Bot
"""

import os
import logging
import urllib
import configparser
import requests
import random

# Grab the Bot OAuth token from the environment.
# BOT_TOKEN = os.environ["BOT_TOKEN"]

# Define the URL of the targeted Slack API resource.
# We'll send our replies there.


def lambda_handler(data, context):
    '''
        Handle an incoming HTTP request from a groupme chat-bot.
    '''

    '''
        First we want to grab the BOT_TOKEN
        We will first check if the token is giving via local test harness
        If Not we will load via environment variables 
    '''

    if 'local' in data:
        config = configparser.ConfigParser()
        config.read('config.ini')
        BOT_TOKEN = config['FF_BOT']['GROUPME_TOKEN']
        BOT_ID = config['FF_BOT']['BOT_ID']
    else:
        BOT_TOKEN = os.environ['BOT_TOKEN']
        BOT_ID=os.environ['BOT_ID']

    ''' 
        We need to discriminate between events generated by 
        the users, which we want to process and handle, 
        and those generated by the bot. 
    '''

    if data['name'] == 'bigdog':
        print(data['user_id'])
        logging.warn("Ignore bot event")
    else:
        # Parse through the text to see if any specific commands are referenced
        text = data["text"]
        formatted_output = parse_group_text(text)
        
        if formatted_output != "None":
           data = {'bot_id': BOT_ID, 'text': formatted_output}
           headers = {'Content-Type': 'application/json'}
           url = 'https://api.groupme.com/v3/bots/post'

           req = requests.post(url=url, headers=headers, json=data, verify=False)
    # Everything went fine.
    return "200 OK"

def parse_group_text(text):
    '''
        Parses the string for known commands
    '''
    dogs_meme_list=['https://cdn.discordapp.com/attachments/507983124391788554/507985421511163904/image03.jpg',
        'https://cdn.discordapp.com/attachments/507983124391788554/507987555485089792/drake-dog-diamond-pet-views.png',
        'https://i.groupme.com/231x218.jpeg.9eac248103134c28a1697c717f393c96.large',
        'https://i.groupme.com/474x355.jpeg.84ee81e8e12b4b8082376efec162ac09.large',
        'https://i.groupme.com/474x311.jpeg.714a43e2d31e4bb18c2b84e06460df9e.large',
        'https://i.groupme.com/796x1632.jpeg.492a490e13eb4375b7dcbc7f5fae9fed.large']

    string = text.split()
    for word in string:
        if word == "DAWGS":
            return(random.choice(dogs_meme_list))
    else:
        return("None")
